version: "3.7"

services:
    redis:
        build:
            context: .
            dockerfile: Dockerfile_redis
        ports:
            - 6379:6379
    
    mysql:
        build:
            context: .
            dockerfile: Dockerfile_mysql
        ports:
            - 3306:3306